### ISSUE TITLE
Missing "." in class

### ISSUE THREAD

**Issue by amaisano** [jennyvallon/anklebootstrap#1]
The selector "col-xs-10point5" is missing a leading "." on the "float: left" rule, around line 1622.

**Comment by jennyvallon** [comment]
You are great! I will update that immediately. 

Many thanks!
Has it been helpful?

JV

Sent from my iPhone, 
so please excuse any mistakes.

**Comment by jennyvallon** [comment]
v1.3 of anklebootstrap fixes those issues as well as removes some -12point5 classes, replacing them with -point5 classes. 
Thanks for the heads up.
